# Generated by Django 4.1.7 on 2023-06-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='bank',
            new_name='bank_name',
        ),
    ]
